In [60]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.metrics import accuracy_score, classification_report

In [61]:
#KNN 1 to 10
#Load dataset name = BreastCancer
#Report : accuracy score
df=pd.read_csv('BreastCancer.csv',index_col=0)  #index col 0 means to drop *Code* Column
# df.columns
# 'Code', 'Clump', 'UniCell_Size', 'Uni_CellShape', 'MargAdh', 'SEpith',
# 'BareN', 'BChromatin', 'NoemN', 'Mitoses', 'Class'
# df.dtypes no str expect class
df.head()

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
Code,,,,,,,,,,
61634,5,4,3,1,2,2,2,3,1,Benign
63375,9,1,2,6,4,10,7,7,2,Malignant
76389,10,4,7,2,2,8,6,1,1,Malignant
95719,6,10,10,10,8,10,7,10,7,Malignant
128059,1,1,1,1,2,5,5,1,1,Benign

In [62]:
X=df.drop('Class',axis=1)
y=df['Class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=25,stratify=y)

In [63]:
K=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in K:
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train,y_train)
    y_pred=knn.predict(X_test)
    scores.append([k,accuracy_score(y_test,y_pred)])
df_scored=pd.DataFrame(scores,columns=['k','score']).sort_values(by='score',ascending=False)
print(df_scored)

    k     score
4   5  0.976190
2   3  0.971429
8   9  0.961905
7   8  0.961905
3   4  0.961905
6   7  0.961905
9  10  0.961905
0   1  0.957143
5   6  0.952381
1   2  0.933333

In [64]:
df=pd.read_csv('HR_comma_sep.csv',index_col=0)
df.head()

,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
satisfaction_level,,,,,,,,,
0.38,0.53,2,157,3,0,1,0,sales,low
0.80,0.86,5,262,6,0,1,0,sales,medium
0.10,0.77,6,247,4,0,1,0,sales,low
0.92,0.85,5,259,5,0,1,0,sales,low
0.89,1.00,5,224,5,0,1,0,sales,low

In [65]:
df=pd.get_dummies(df,drop_first=True)
df.head()

,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department_RandD,Department_accounting,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_low,salary_medium
satisfaction_level,,,,,,,,,,,,,,,,,,
0.38,0.53,2,157,3,0,1,0,False,False,False,False,False,False,True,False,False,True,False
0.80,0.86,5,262,6,0,1,0,False,False,False,False,False,False,True,False,False,False,True
0.10,0.77,6,247,4,0,1,0,False,False,False,False,False,False,True,False,False,True,False
0.92,0.85,5,259,5,0,1,0,False,False,False,False,False,False,True,False,False,True,False
0.89,1.00,5,224,5,0,1,0,False,False,False,False,False,False,True,False,False,True,False

In [66]:
X=df.drop('left',axis=1)
y=df['left']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=25,stratify=y)
K=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in K:
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train,y_train)
    y_pred=knn.predict(X_test)
    scores.append([k,accuracy_score(y_test,y_pred)])
df_scored=pd.DataFrame(scores,columns=['k','score']).sort_values(by='score',ascending=False)
print(df_scored)

    k     score
0   1  0.945543
7   8  0.942209
5   6  0.941765
9  10  0.939987
1   2  0.939542
3   4  0.939542
8   9  0.939320
6   7  0.936875
2   3  0.936430
4   5  0.935986

In [67]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train_scaled,y_train)
y_pred=knn.predict(X_test_scaled)
print(accuracy_score(y_test,y_pred))

0.9575461213603023

In [68]:
K=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in K:
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled,y_train)
    y_pred=knn.predict(X_test_scaled)
    scores.append([k,accuracy_score(y_test,y_pred)])
df_scored=pd.DataFrame(scores,columns=['k','score']).sort_values(by='score',ascending=False)
print(df_scored)

    k     score
0   1  0.957546
1   2  0.953101
2   3  0.945543
5   6  0.943765
3   4  0.942654
7   8  0.942209
9  10  0.940653
6   7  0.939320
8   9  0.937986
4   5  0.937542

In [69]:
scaler=MinMaxScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)
K=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in K:
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled,y_train)
    y_pred=knn.predict(X_test_scaled)
    scores.append([k,accuracy_score(y_test,y_pred)])
df_scored=pd.DataFrame(scores,columns=['k','score']).sort_values(by='score',ascending=False)
print(df_scored)

    k     score
0   1  0.956879
1   2  0.952878
2   3  0.943543
3   4  0.940431
5   6  0.939987
7   8  0.938875
9  10  0.937986
6   7  0.937986
8   9  0.937097
4   5  0.935541

In [71]:
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train_scaled,y_train)
y_pred=knn.predict(X_test_scaled)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.96      0.97      3429
           1       0.88      0.95      0.91      1070

    accuracy                           0.96      4499
   macro avg       0.93      0.95      0.94      4499
weighted avg       0.96      0.96      0.96      4499